# pull official base image
FROM node:16-alpine

# set working directory


WORKDIR /app



# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --no-optional && npm cache clean --force
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH


# add app
COPY . ./

# start app
CMD ["npm", "start"]