version: '3'

services:
  db:
    image: postgres
    container_name: pg_container
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
  backend-django:
    container_name: backend-django
    build: ./backend
    command: sh -c  "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    stdin_open: true
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    tty: true
    depends_on:
      - db
  frontend-react:
    container_name: frontend-react
    build: ./frontend
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules  
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true 
    depends_on:
      - backend-django
    command: sh -c "npm start"
    ports:
      - "3000:3000"
  
  