FROM python:3.11.0a7-alpine3.15
ENV PYTHONUNBUFFERED 1
RUN mkdir /backend
RUN apk update \
  # psycopg2 dependencies
  && apk add --virtual build-deps gcc python3-dev musl-dev libpq-dev python3-dev\
  # Pillow dependencies
  && apk add jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev \  
  # CFFI dependencies
  && apk add libffi-dev py-cffi \  
  # DB connectors
  && apk add mariadb-connector-c-dev mysql mysql-client mariadb-dev build-base \
  # Fonts
  && apk add ttf-opensans \
  # OpenSSL
  # && apk add build-base libressl-dev libffi-dev cargo openssl-dev \
  # Others
  && apk add libxml2-dev libxslt-dev py3-lxml cairo-dev pango-dev gdk-pixbuf-dev g++
  
RUN pip install psycopg2-binary

WORKDIR /backend
ADD requirements /backend/requirements
RUN pip install -r requirements/base.txt